import type { Language } from "@/i18n/types";

/** Textos del atlas en los tres idiomas de la app. {llaves} se reemplazan con `fmt`. */
const es = {
  title: "Dónde se investiga",
  subWorld: "Estudios por país según la institución de los autores · OpenAlex",
  subCol: "Estudios con institución colombiana, por departamento · OpenAlex",
  tabWorld: "Mundo",
  tabCol: "Colombia",
  hint: "Arrastra para girar · Rueda para acercar · Clic en un país",
  zoomIn: "Acercar",
  zoomOut: "Alejar",
  resetView: "Restablecer vista",
  pause: "Pausar rotación",
  play: "Reanudar rotación",
  viewAll: "Ver todo el país",
  search: "Buscar país…",
  studies: "estudios",
  worldEyebrow: "Vista global",
  worldTitle: "Dónde se investiga este tema",
  worldDesc: "Cada país se colorea según cuántos estudios tienen al menos una institución en él. Toca un país para ver su detalle.",
  statTotal: "estudios en OpenAlex",
  statCountries: "países con investigación",
  statTop3: "de los estudios están en los 3 países con más investigación",
  rankWorld: "Países con más estudios",
  cardRank: "#{rank} de {n} países",
  cardShare: "de los estudios",
  cardStudies: "estudios con institución en este país",
  noResearch: "Ningún estudio de estos resultados tiene instituciones en este país.",
  worldNote:
    "Un estudio cuenta en cada país donde algún autor tiene institución, por eso la suma de países supera el total. Es un conteo exacto sobre todos los resultados de OpenAlex.",
  goColombia: "Ver Colombia por departamentos",
  colEyebrow: "Vista nacional",
  colTotal: "estudios con institución colombiana",
  colShare: "de los estudios del tema",
  colSampleLine: "Se ubican los {n} más relevantes de {total}.",
  colInst: "instituciones ubicadas",
  colDepts: "departamentos con estudios",
  rankDept: "Departamentos con más estudios",
  rankInst: "Instituciones más activas",
  unlocated: "{n} instituciones no tienen coordenadas en OpenAlex y no se pueden ubicar.",
  colNote: "Un estudio cuenta una vez por departamento aunque tenga varias instituciones allí.",
  noColombia:
    "Ningún estudio de estos resultados tiene instituciones colombianas. Es una señal de posible vacío contextual: conviene confirmarlo con una búsqueda más amplia antes de afirmarlo.",
  depStudies: "estudios con institución en este departamento",
  depInstitutions: "Instituciones",
  depEmpty: "Ningún estudio analizado tiene instituciones en este departamento.",
  backCol: "← Ver toda Colombia",
  tipStudies: "{n} estudios",
  insetName: "San Andrés y Prov.",
  closeCard: "Cerrar ficha",
  worksCountry: "Estudios de este país (los más relevantes)",
  worksColombia: "Estudios con institución colombiana (los más relevantes)",
  worksDept: "Estudios de este departamento (los más relevantes)",
  worksLoading: "Cargando estudios…",
  worksError: "No se pudieron cargar los estudios. Intenta de nuevo.",
  worksEmpty: "No hay estudios para mostrar.",
  worksMore: "Mostrando los {n} más relevantes de {total}. Cada título abre el estudio en una pestaña nueva.",
} as const;

type Strings = { [K in keyof typeof es]: string };

const en: Strings = {
  title: "Where it is researched",
  subWorld: "Studies per country by author institution · OpenAlex",
  subCol: "Studies with a Colombian institution, by department · OpenAlex",
  tabWorld: "World",
  tabCol: "Colombia",
  hint: "Drag to rotate · Scroll to zoom · Click a country",
  zoomIn: "Zoom in",
  zoomOut: "Zoom out",
  resetView: "Reset view",
  pause: "Pause rotation",
  play: "Resume rotation",
  viewAll: "View whole country",
  search: "Search country…",
  studies: "studies",
  worldEyebrow: "Global view",
  worldTitle: "Where this topic is researched",
  worldDesc: "Each country is shaded by how many studies have at least one institution in it. Tap a country for details.",
  statTotal: "studies in OpenAlex",
  statCountries: "countries with research",
  statTop3: "of the studies are in the 3 countries with the most research",
  rankWorld: "Countries with the most studies",
  cardRank: "#{rank} of {n} countries",
  cardShare: "of the studies",
  cardStudies: "studies with an institution in this country",
  noResearch: "None of these results has an institution in this country.",
  worldNote:
    "A study counts in every country where an author has an institution, so the country sum exceeds the total. It is an exact count over all OpenAlex results.",
  goColombia: "View Colombia by department",
  colEyebrow: "National view",
  colTotal: "studies with a Colombian institution",
  colShare: "of the topic's studies",
  colSampleLine: "The {n} most relevant of {total} are located.",
  colInst: "located institutions",
  colDepts: "departments with studies",
  rankDept: "Departments with the most studies",
  rankInst: "Most active institutions",
  unlocated: "{n} institutions have no coordinates in OpenAlex and cannot be located.",
  colNote: "A study counts once per department even if it has several institutions there.",
  noColombia:
    "None of these results has Colombian institutions. This hints at a possible contextual gap: confirm it with a broader search before claiming it.",
  depStudies: "studies with an institution in this department",
  depInstitutions: "Institutions",
  depEmpty: "No analysed study has institutions in this department.",
  backCol: "← View all of Colombia",
  tipStudies: "{n} studies",
  insetName: "San Andrés & Prov.",
  closeCard: "Close card",
  worksCountry: "Studies from this country (most relevant)",
  worksColombia: "Studies with a Colombian institution (most relevant)",
  worksDept: "Studies from this department (most relevant)",
  worksLoading: "Loading studies…",
  worksError: "The studies could not be loaded. Try again.",
  worksEmpty: "No studies to show.",
  worksMore: "Showing the {n} most relevant of {total}. Each title opens the study in a new tab.",
};

const pt: Strings = {
  title: "Onde se pesquisa",
  subWorld: "Estudos por país segundo a instituição dos autores · OpenAlex",
  subCol: "Estudos com instituição colombiana, por departamento · OpenAlex",
  tabWorld: "Mundo",
  tabCol: "Colômbia",
  hint: "Arraste para girar · Role para aproximar · Clique em um país",
  zoomIn: "Aproximar",
  zoomOut: "Afastar",
  resetView: "Redefinir vista",
  pause: "Pausar rotação",
  play: "Retomar rotação",
  viewAll: "Ver o país todo",
  search: "Buscar país…",
  studies: "estudos",
  worldEyebrow: "Visão global",
  worldTitle: "Onde este tema é pesquisado",
  worldDesc: "Cada país é colorido conforme quantos estudos têm ao menos uma instituição nele. Toque em um país para ver o detalhe.",
  statTotal: "estudos no OpenAlex",
  statCountries: "países com pesquisa",
  statTop3: "dos estudos estão nos 3 países com mais pesquisa",
  rankWorld: "Países com mais estudos",
  cardRank: "#{rank} de {n} países",
  cardShare: "dos estudos",
  cardStudies: "estudos com instituição neste país",
  noResearch: "Nenhum estudo destes resultados tem instituições neste país.",
  worldNote:
    "Um estudo conta em cada país onde algum autor tem instituição, por isso a soma dos países supera o total. É uma contagem exata sobre todos os resultados do OpenAlex.",
  goColombia: "Ver a Colômbia por departamentos",
  colEyebrow: "Visão nacional",
  colTotal: "estudos com instituição colombiana",
  colShare: "dos estudos do tema",
  colSampleLine: "São localizados os {n} mais relevantes de {total}.",
  colInst: "instituições localizadas",
  colDepts: "departamentos com estudos",
  rankDept: "Departamentos com mais estudos",
  rankInst: "Instituições mais ativas",
  unlocated: "{n} instituições não têm coordenadas no OpenAlex e não podem ser localizadas.",
  colNote: "Um estudo conta uma vez por departamento mesmo com várias instituições nele.",
  noColombia:
    "Nenhum estudo destes resultados tem instituições colombianas. É um sinal de possível lacuna contextual: confirme com uma busca mais ampla antes de afirmar.",
  depStudies: "estudos com instituição neste departamento",
  depInstitutions: "Instituições",
  depEmpty: "Nenhum estudo analisado tem instituições neste departamento.",
  backCol: "← Ver toda a Colômbia",
  tipStudies: "{n} estudos",
  insetName: "San Andrés e Prov.",
  closeCard: "Fechar ficha",
  worksCountry: "Estudos deste país (os mais relevantes)",
  worksColombia: "Estudos com instituição colombiana (os mais relevantes)",
  worksDept: "Estudos deste departamento (os mais relevantes)",
  worksLoading: "Carregando estudos…",
  worksError: "Não foi possível carregar os estudos. Tente novamente.",
  worksEmpty: "Não há estudos para mostrar.",
  worksMore: "Mostrando os {n} mais relevantes de {total}. Cada título abre o estudo em uma nova aba.",
};

const dictionaries: Record<Language, Strings> = { es, en, pt };

export type AtlasStringKey = keyof typeof es;

export function atlasStrings(language: Language): (key: AtlasStringKey, vars?: Record<string, string | number>) => string {
  const dict = dictionaries[language] ?? es;
  return (key, vars) =>
    Object.entries(vars ?? {}).reduce((text, [name, value]) => text.replaceAll(`{${name}}`, String(value)), dict[key] ?? es[key]);
}
